CREATE TABLE [dbo].[staging.title](
	[TitleSK] [int] NOT NULL,
	[title] [varchar](80) NULL,
	[type] [char](12) NULL,
	[price] [money] NULL,
	[pubdate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[TitleSK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO